#!/bin/bash
#PBS -N balance
#PBS -A ccsd
#PBS -l qos=std,nodes=4:ppn=32,walltime=00:02:00
#PBS -q batch
#PBS -W group_list=cades-ccsd
#PBS -e balance.e
#PBS -o balance.o

cd ~/mpi_balance
pwd

## module names can vary on different platforms
module load R
echo "loaded R"
module list

## prevent warning when fork is used with MPI
export OMPI_MCA_mpi_warn_on_fork=0

mpirun -np 16 --map-by ppr:4:node Rscript hello_balance.R
